name: SportzxSerieA Scraper

on:
  workflow_dispatch:  # Permette di eseguire il workflow manualmente
  schedule:
    - cron: '*/7 * * * *'  # Esegue ogni 8 ore (es. 00:00, 08:00, 16:00 UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v4  # Aggiornato alla versione più recente
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5  # Aggiornato alla versione più recente
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pycryptodome

      - name: Run Sportzx Scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python SportzxSerieA.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add SerieA_Sportzx.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push origin main --force
        continue-on-error: true
