name: SportsOnline 1 Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper beautifulsoup4

      - name: Delete old W3U/EventiS.w3u file
        run: |
          if [ -f "W3U/EventiS.w3u" ]; then
            rm W3U/EventiS.w3u
            echo "File EventiS.w3u eliminato."
          else
            echo "Nessun file EventiS.w3u da eliminare."
          fi

      - name: Run SportsOnline 1 Scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python sportsonline1.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add W3U/EventiS.w3u
          git commit -m "Rigenerato EventiS.w3u con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push origin main --force
        continue-on-error: true
