name: Twitch Scraper

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '0 */5 * * *'  # Esegue ogni 3 ore: 0:00, 3:00, 6:00, 9:00, 12:00, 15:00, 18:00, 21:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlink

      - name: Run Twitch scraper
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python twitch_m3u8.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add twitch_streams.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
